/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;


import br.com.projeto.dao.FornecedorDAO;
import br.com.projeto.dao.ProdutoDAO;
import br.com.projeto.model.Fornecedor;
import br.com.projeto.model.Produto;
import br.com.projeto.model.Utilitarios;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Charlie
 */
public class frmProdutos extends javax.swing.JFrame {

    /**
     * Creates new form frmCliente
     */
    public void listar() {
        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> lista = dao.listarProduto();
        DefaultTableModel dados = (DefaultTableModel) tabelaProdutosjTable1.getModel();
        dados.setNumRows(0);
        for (Produto p : lista) {
            dados.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getPreco(),
                p.getQtd_estoque(),
                p.getFornecedor().getNome()
            });
        }
    }

    public frmProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelDeGuiasjTabbedPane4 = new javax.swing.JTabbedPane();
        guia_dados_pessoais = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cbFornecedorjComboBox1 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        txtQtdEstoque = new javax.swing.JTextField();
        consultaProdutosjPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtPesquisarDescricao = new javax.swing.JTextField();
        btnPesquisarNome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutosjTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnNovojButton2 = new javax.swing.JButton();
        btnSalvarjButton3 = new javax.swing.JButton();
        btnEditarjButton4 = new javax.swing.JButton();
        btnExcluirjButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de produtos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Produtos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
        );

        painelDeGuiasjTabbedPane4.setBackground(new java.awt.Color(255, 255, 255));
        painelDeGuiasjTabbedPane4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Codigo:");

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDescricao.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txtDescricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Descrição:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Preço:");

        txtPreco.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnPesquisar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Fornecedor:");

        cbFornecedorjComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbFornecedorjComboBox1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbFornecedorjComboBox1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbFornecedorjComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbFornecedorjComboBox1MouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Qtd. estoque:");

        txtQtdEstoque.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        javax.swing.GroupLayout guia_dados_pessoaisLayout = new javax.swing.GroupLayout(guia_dados_pessoais);
        guia_dados_pessoais.setLayout(guia_dados_pessoaisLayout);
        guia_dados_pessoaisLayout.setHorizontalGroup(
            guia_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guia_dados_pessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(guia_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guia_dados_pessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(cbFornecedorjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(guia_dados_pessoaisLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(guia_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(guia_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(guia_dados_pessoaisLayout.createSequentialGroup()
                                .addGroup(guia_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(guia_dados_pessoaisLayout.createSequentialGroup()
                                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel17))
                                    .addComponent(txtDescricao))
                                .addGap(18, 18, 18)
                                .addGroup(guia_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPesquisar))))))
                .addContainerGap(857, Short.MAX_VALUE))
        );
        guia_dados_pessoaisLayout.setVerticalGroup(
            guia_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guia_dados_pessoaisLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(guia_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(guia_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(guia_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(btnPesquisar)))
                .addGap(18, 18, 18)
                .addGroup(guia_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(guia_dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbFornecedorjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137))
        );

        guia_dados_pessoaisLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDescricao, txtPreco, txtQtdEstoque});

        painelDeGuiasjTabbedPane4.addTab("Dados do produto", guia_dados_pessoais);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Descrição:");

        txtPesquisarDescricao.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtPesquisarDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarDescricaoKeyReleased(evt);
            }
        });

        btnPesquisarNome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnPesquisarNome.setText("Pesquisar");
        btnPesquisarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarNomeActionPerformed(evt);
            }
        });

        tabelaProdutosjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod.", "Descrição", "Preço", "Qtd. Estoque", "Fornecedor"
            }
        ));
        tabelaProdutosjTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosjTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProdutosjTable1);

        javax.swing.GroupLayout consultaProdutosjPanel3Layout = new javax.swing.GroupLayout(consultaProdutosjPanel3);
        consultaProdutosjPanel3.setLayout(consultaProdutosjPanel3Layout);
        consultaProdutosjPanel3Layout.setHorizontalGroup(
            consultaProdutosjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaProdutosjPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(txtPesquisarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnPesquisarNome)
                .addContainerGap(710, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        consultaProdutosjPanel3Layout.setVerticalGroup(
            consultaProdutosjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaProdutosjPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(consultaProdutosjPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtPesquisarDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelDeGuiasjTabbedPane4.addTab("Consulta de produtos", consultaProdutosjPanel3);

        btnNovojButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnNovojButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconfinder_sign-add_299068.png"))); // NOI18N
        btnNovojButton2.setText("NOVO");
        btnNovojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovojButton2ActionPerformed(evt);
            }
        });

        btnSalvarjButton3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnSalvarjButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar_2.png"))); // NOI18N
        btnSalvarjButton3.setText("SALVAR");
        btnSalvarjButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarjButton3ActionPerformed(evt);
            }
        });

        btnEditarjButton4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnEditarjButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar_1.png"))); // NOI18N
        btnEditarjButton4.setText("EDITAR");
        btnEditarjButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarjButton4ActionPerformed(evt);
            }
        });

        btnExcluirjButton5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnExcluirjButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconfinder_edit-delete_118920.png"))); // NOI18N
        btnExcluirjButton5.setText("EXCLUIR");
        btnExcluirjButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirjButton5ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PRINT (2).png"))); // NOI18N
        jButton1.setText("imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnNovojButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnSalvarjButton3)
                .addGap(73, 73, 73)
                .addComponent(btnEditarjButton4)
                .addGap(77, 77, 77)
                .addComponent(btnExcluirjButton5)
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEditarjButton4, btnExcluirjButton5, btnNovojButton2, btnSalvarjButton3});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovojButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarjButton3)
                    .addComponent(btnEditarjButton4)
                    .addComponent(btnExcluirjButton5)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEditarjButton4, btnExcluirjButton5, btnNovojButton2, btnSalvarjButton3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelDeGuiasjTabbedPane4)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDeGuiasjTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarjButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarjButton3ActionPerformed
        // cadastrar produto
        Produto obj = new Produto();
        obj.setDescricao(txtDescricao.getText());
        obj.setPreco(Integer.valueOf(txtPreco.getText()));
        obj.setQtd_estoque(Integer.valueOf(txtQtdEstoque.getText()));

        obj.setFornecedor((Fornecedor) cbFornecedorjComboBox1.getSelectedItem());

        ProdutoDAO dao = new ProdutoDAO();
        dao.cadastrarProduto(obj);
        new Utilitarios().limpaTela(guia_dados_pessoais);
    }//GEN-LAST:event_btnSalvarjButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // método listar
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void tabelaProdutosjTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosjTable1MouseClicked
        // clicar tabela
        painelDeGuiasjTabbedPane4.setSelectedIndex(0);
        txtCodigo.setText(tabelaProdutosjTable1.getValueAt(tabelaProdutosjTable1.getSelectedRow(), 0).toString());
        txtDescricao.setText(tabelaProdutosjTable1.getValueAt(tabelaProdutosjTable1.getSelectedRow(), 1).toString());
        txtPreco.setText(tabelaProdutosjTable1.getValueAt(tabelaProdutosjTable1.getSelectedRow(), 2).toString());
        txtQtdEstoque.setText(tabelaProdutosjTable1.getValueAt(tabelaProdutosjTable1.getSelectedRow(), 3).toString());

        Fornecedor f = new Fornecedor();
        FornecedorDAO daof = new FornecedorDAO();
        f = daof.buscarFornecedor(tabelaProdutosjTable1.getValueAt(tabelaProdutosjTable1.getSelectedRow(), 4).toString());
        cbFornecedorjComboBox1.removeAllItems();
        cbFornecedorjComboBox1.getModel().setSelectedItem(f);
        
      

    }//GEN-LAST:event_tabelaProdutosjTable1MouseClicked

    private void btnEditarjButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarjButton4ActionPerformed
        // alterar cliente
        Produto obj = new Produto();
        obj.setId(Integer.valueOf(txtCodigo.getText()));
        obj.setDescricao(txtDescricao.getText());
        obj.setPreco(Double.valueOf(txtPreco.getText()));
        obj.setQtd_estoque(Integer.valueOf(txtQtdEstoque.getText()));

        //para o fornecedor é diferente
        Fornecedor f = new Fornecedor();
        f = (Fornecedor) cbFornecedorjComboBox1.getSelectedItem();
        obj.setFornecedor(f);

        ProdutoDAO daop = new ProdutoDAO();
        daop.alterarProduto(obj);

        new Utilitarios().limpaTela(guia_dados_pessoais);
    }//GEN-LAST:event_btnEditarjButton4ActionPerformed

    private void btnExcluirjButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirjButton5ActionPerformed
        // excluir cliente
        Produto obj = new Produto();
        obj.setId(Integer.valueOf(txtCodigo.getText()));

        ProdutoDAO dao = new ProdutoDAO();
        dao.excluirProduto(obj);
        new Utilitarios().limpaTela(guia_dados_pessoais);
    }//GEN-LAST:event_btnExcluirjButton5ActionPerformed

    private void btnPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarNomeActionPerformed
        // botão pesquisar
        String nome = "%" + txtPesquisarDescricao.getText() + "%";
        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> lista = dao.pesquisarProdutoPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaProdutosjTable1.getModel();
        dados.setNumRows(0);
        for (Produto p : lista) {
            dados.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getPreco(),
                p.getQtd_estoque(),
                p.getFornecedor().getNome()
            });
        }

    }//GEN-LAST:event_btnPesquisarNomeActionPerformed

    private void txtPesquisarDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarDescricaoKeyReleased
        // pesquisar digitando o nome
        String nome = "%" + txtPesquisarDescricao.getText() + "%";
        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> lista = dao.pesquisarProdutoPorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaProdutosjTable1.getModel();
        dados.setNumRows(0);
        for (Produto p : lista) {
            dados.addRow(new Object[]{
                p.getId(),
                p.getDescricao(),
                p.getPreco(),
                p.getQtd_estoque(),
                p.getFornecedor().getNome()
            });

        }

    }//GEN-LAST:event_txtPesquisarDescricaoKeyReleased

    private void btnNovojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovojButton2ActionPerformed
        // TODO add your handling code here:
        Utilitarios util = new Utilitarios();
        util.limpaTela(guia_dados_pessoais);
    }//GEN-LAST:event_btnNovojButton2ActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // botão buscar produto por nome
      String nome = txtDescricao.getText();
      Produto obj = new Produto();
      ProdutoDAO dao = new ProdutoDAO();
      obj = dao.buscarProduto(nome);
      
      cbFornecedorjComboBox1.removeAllItems();
      if(obj.getDescricao()!=null){
      txtCodigo.setText(String.valueOf(obj.getId()));
      txtDescricao.setText(obj.getDescricao());
      txtPreco.setText(String.valueOf(obj.getPreco()));
      txtQtdEstoque.setText(String.valueOf(obj.getQtd_estoque()));
      
      Fornecedor f = new Fornecedor();
      FornecedorDAO daof = new FornecedorDAO();
      f= daof.buscarFornecedor(obj.getFornecedor().getNome());
      cbFornecedorjComboBox1.getModel().setSelectedItem(f);
      }else{
      JOptionPane.showMessageDialog(null,"produto não encontrado!");
      }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void cbFornecedorjComboBox1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbFornecedorjComboBox1AncestorAdded
  
    }//GEN-LAST:event_cbFornecedorjComboBox1AncestorAdded

    private void cbFornecedorjComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbFornecedorjComboBox1MouseClicked
       // carrega combobox de fornecedores
        FornecedorDAO dao = new FornecedorDAO();
        List<Fornecedor>listaFornecedor = dao.listarFornecedores();
        cbFornecedorjComboBox1.removeAllItems();
        for(Fornecedor f : listaFornecedor){
            cbFornecedorjComboBox1.addItem(f);
        }
    }//GEN-LAST:event_cbFornecedorjComboBox1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new relatorios.relProdutos();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarjButton4;
    private javax.swing.JButton btnExcluirjButton5;
    private javax.swing.JButton btnNovojButton2;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPesquisarNome;
    private javax.swing.JButton btnSalvarjButton3;
    private javax.swing.JComboBox cbFornecedorjComboBox1;
    public javax.swing.JPanel consultaProdutosjPanel3;
    private javax.swing.JPanel guia_dados_pessoais;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane painelDeGuiasjTabbedPane4;
    private javax.swing.JTable tabelaProdutosjTable1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPesquisarDescricao;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQtdEstoque;
    // End of variables declaration//GEN-END:variables
}
